INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Leola', '39', '17540');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Akron Borough', '37', '17501');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Caernarvon Township', '46', '17555');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Christiana Borough', '34', '17509');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Columbia Borough', '35', '17512');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Conestoga Township', '39', '17516');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Denver Borough', '32', '17517');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Drumore Township', '47', '17518');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('East Donegal Township', '44', '15628');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('East Earl Township', '46', '17519');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('East Petersburg Borough', '39', '17520');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Elizabeth Township', '41', '15037');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Ephrata Borough', '37', '17522');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Fulton Township', '47', '17322');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Lancaster City', '39', '17601');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Lancaster City', '39', '17602');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Lancaster City', '39', '17603');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Lancaster Township', '39', '17611');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Lititz Borough', '41', '17543');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Little Britain Township', '47', '17866');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Manheim Township', '43', '17545');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Manor Township', '39', '15665');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Marietta Borough', '44', '17547');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Millersville Borough', '39', '17551');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Mount Joy Township', '44', '17552');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Mountville Borough', '39', '17554');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('New Holland Borough', '46', '17557');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Paradise Township', '38', '17562');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Penn Township', '42', '15675');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Pequea Township', '39', '17565');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Providence Township', '47', '17560');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Quarryville Borough', '47', '17566');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Sadsbury Township', '34', '16066');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Salisbury Township', '38', '15558');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Strasburg Township', '48', '17579');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Terre Hill Borough', '46', '17581');
INSERT INTO municipality (municipality_name, service_area_code, zip_code) VALUES ('Warwick Township', '41', '15762');
