INSERT INTO school_district (nces_dist, district_name) VALUES ('4206270', 'Cocalico SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4206360', 'Columbia Borough SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4206480', 'Conestoga Valley SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4207650', 'Donegal SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4208820', 'Eastern Lancaster County SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4209120', 'Elizabethtown Area SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4209270', 'Ephrata Area SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4211790', 'Hempfield SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4213110', 'Lampeter-Strasburg SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4280270', 'Lancaster County CTC');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4213140', 'Lancaster SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4289230', 'Lancaster-Lebanon IU 13');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4214550', 'Manheim Central SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4214580', 'Manheim Township SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4200755', 'Millersville University of PA');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4218630', 'Penn Manor SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4218900', 'Pequea Valley SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4221810', 'Solanco SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4224960', 'Warwick SD');
INSERT INTO school_district (nces_dist, district_name) VALUES ('4200026', 'La Academia Partnership CS');
INSERT INTO school_district (nces_dist, district_name) VALUES ('PRIVATE', 'Private School, No District');
INSERT INTO school_district (nces_dist, district_name) VALUES ('HOMESCH', 'Homeschooled');