INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (32, 'Adamstown Area Library', 'Adamstown Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (37, 'Ephrata Public Library', 'Akron Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Bart Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (32, 'Adamstown Area Library', 'Brecknock Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (46, 'Eastern Lancaster County Library', 'Caernarvon Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (34, 'Moores Memorial Library', 'Christiana Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (37, 'Ephrata Public Library', 'Clay Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Colerain Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (35, 'Columbia Public Library', 'Columbia Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Conestoga Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (36, 'Elizabethtown Public Library', 'Conoy Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (32, 'Adamstown Area Library', 'Denver Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Drumore Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (32, 'Adamstown Area Library', 'East Cocalico Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (44, 'Milanof-Schock Library', 'East Donegal Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'East Drumore Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (46, 'Eastern Lancaster County Library', 'East Earl Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'East Hempfield Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'East Lampeter Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'East Petersburg Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (46, 'Eastern Lancaster County Library', 'Earl Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Eden Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (41, 'Lititz Public Library', 'Elizabeth Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (36, 'Elizabethtown Public Library', 'Elizabethtown Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (37, 'Ephrata Public Library', 'Ephrata Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (37, 'Ephrata Public Library', 'Ephrata Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Fulton Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Lancaster City');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Lancaster Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (38, 'Pequea Valley Public Library', 'Leacock Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (41, 'Lititz Public Library', 'Lititz Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Little Britain Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (42, 'Manheim Community Library', 'Manheim Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (43, 'Manheim Township Public Library', 'Manheim Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Manor Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (44, 'Milanof-Schock Library', 'Marietta Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Martic Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Millersville Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (44, 'Milanof-Schock Library', 'Mount Joy Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (44, 'Milanof-Schock Library', 'Mount Joy Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Mountville Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (46, 'Eastern Lancaster County Library', 'New Holland Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (38, 'Pequea Valley Public Library', 'Paradise Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (42, 'Manheim Community Library', 'Penn Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Pequea Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Providence Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (47, 'Quarryville Library', 'Quarryville Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (42, 'Manheim Community Library', 'Rapho Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (34, 'Moores Memorial Library', 'Sadsbury Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (38, 'Pequea Valley Public Library', 'Salisbury Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (48, 'Strasburg-Heisler Library', 'Strasburg Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (48, 'Strasburg-Heisler Library', 'Strasburg Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (46, 'Eastern Lancaster County Library', 'Terre Hill Borough');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'Uppr Leacock Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (32, 'Adamstown Area Library', 'WestCoclico Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (36, 'Elizabethtown Public Library', 'WestDonegal Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'WestEarl Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'WestHempfield Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (39, 'Lancaster Public Library', 'WestLampeter Township');
INSERT INTO service_area (service_area_code, library_name, municipality_name) VALUES (41, 'Lititz Public Library', 'Warwick Township');